name:                wordle-helper
version:             0.1.0.0
github:              "githubuser/wordle-helper"
license:             BSD3
author:              "Agnelli Alessandro"
maintainer:          "agnelli.jedi@gmail.com"
copyright:           "2022 Agnelli Alessandro"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wordle-helper#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wordle-helper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle-helper

tests:
  wordle-helper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle-helper
    - HUnit